### ISSUE TITLE
broken action - OUTLOOK_OUTLOOK_GET_MESSAGE

### ISSUE THREAD

**Issue by jmiller558** [ComposioHQ/composio#1099]
Test has been run with multiple message_ids using both the python sdk and in the Web UI.

OUTLOOK_OUTLOOK_LIST_MESSAGES works correctly and returns message information along with the message_id

However, OUTLOOK_OUTLOOK_GET_MESSAGE is returning an error, see screenshots.  Thank you!

![outlook_list_messages](https://github.com/user-attachments/assets/e5b85584-3591-4cf7-bfdc-f479f2b3cb39)
![outlook_get_message](https://github.com/user-attachments/assets/9aa89fda-c94d-40d9-8e36-df1a11510910)

**Comment by plxity** [comment]
@jmiller558 Thanks for reporting this issue, it has been fixed, Can you please check?

**Comment by jmiller558** [comment]
Looks good thanks @plxity 

For my reference, where can I see what's happening under the hood of the Apps/Actions?  I did some looking around the code base here but it wasn't immediately clear

Thank you!
