### ISSUE TITLE
[BUG] [App.SCHEDULER] Error executing action with ComposioToolSet: 'sessionmaker' object has no attribute 'rollback'

### ISSUE THREAD

**Issue by HELIOPOTELICKI** [ComposioHQ/composio#227]
Description:
I am encountering an issue when trying to execute an action using the ComposioToolSet in the composio_langchain library. The specific error I receive is: 'sessionmaker' object has no attribute 'rollback'.

Steps to Reproduce:

Configured the ComposioToolSet with the API key.
Attempted to execute the following action:

```python

from composio_langchain import ComposioToolSet, App

composio_toolset = ComposioToolSet(api_key="my-composio-key")
tools = composio_toolset.get_tools(apps=[App.SCHEDULER])

payload = {
    "webhook_url": "https://83f7-177-101-111-149.ngrok-free.app/google-notifications",
    "cron_pattern": "20 13 * * *",
    "start_date": "2024-06-27",
    "end_date": "2024-06-27",
    "webhook_payload": {
        "message": "Test"
    }
}

tools[0].run(tool_input=payload)
```

Expected Result:
The action should execute without errors, setting up the webhook as specified in the payload.

Actual Result:
I receive the following error:

```bash
HTTPError: {"message":"Failed with response: Error executing action with error: 'sessionmaker' object has no attribute 'rollback'"}
```

Environment:

Python version: 3.11.9
composio_langchain version: 0.3.15
Operating System: Windows 11 Pro

Additional Information:
I have tried updating all dependencies and checking the documentation, but the issue persists.
The same error is obtained when passing the tool to an agent.

I appreciate any help or guidance on how to resolve this issue.

**Comment by shubhras01** [comment]
Thanks for reporting this @HELIOPOTELICKI 
We have rolled out the fix from our side, please try once !

**Comment by utkarsh-dixit** [comment]
Closing this, this issue has been fixed and released. Feel free to re-open this if the issue still persists
