### ISSUE TITLE
Google calendar timezone

### ISSUE THREAD

**Issue by shantanuo** [ComposioHQ/composio#232]
I tried the example code that I found here....

https://docs.composio.dev/guides/examples/todo-to-calendar#putting-it-all-together

This is working as expected. But is there any way to set the time to IST (Indian Standard Time)?

**Comment by sohamganatra** [comment]
It should work out of box ideally! Just try adding to task that we give to agent something like, can you make those events in Indian timezone. Agent with a good model will be smart enough to know how to achieve that.

**Comment by shantanuo** [comment]
I just changed the description by adding that instruction and it worked as expected.

description=f"Use IST (Indian Standard Time). Book slots according to {todo}....

This is really awesome! No programming required? No need of hellish chains like datetime.pytz.now().astimezone() ? What the programmers are supposed to do now?

**Comment by shantanuo** [comment]
I need the description of the task to be added to the calendar like...

todo = '''
    1PM - 3PM -> Code, > Work on pending tasks of chatGPT integration
    5PM - 7PM -> Meeting, > call and discuss pending tasks with developers
    9AM - 12AM -> Learn soemthing > Learn how to use composio effectively 
    8PM - 10PM -> Game > play couter strike and pubG

'''
How do I achieve this?

**Comment by shantanuo** [comment]
Again, mentioning that part in description itself is the key.

description=f"Use IST (Indian Standard Time). Book slots according to {todo}. Label them with the work provided to be done in that time period. Schedule it for today. add the description that is mentioned after greater than sign. Today's date is {date} (it's in YYYY-MM-DD format) and make the timezone be {timezone}.",
