### ISSUE TITLE
Unable to run the example set due to KEYERROR

### ISSUE THREAD

**Issue by ashlytom** [ComposioHQ/composio#262]
Hi, I have experimenting with the composio module for creating different agent workflows. Tried the Competitor Researcher and the Research Assistant. Both the quick samples are breaking half way through. Best i can understand the issue is orignatin from here 
"\site-packages\composio_langchain\toolset.py" and "site-packages\langchain_core\runnables\base.py"

Whatever header has been set internal is not the one the script is using. 

Attaching errors:
**Competitor Researcher** 
File "Lib\concurrent\futures\thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

**Research Assistant**
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  "composio\utils\shared.py", line 278, in get_signature_format_from_schema_params      
    param_default = param_schema.get("default", FALLBACK_VALUES[param_type])
                                                ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: None

**Comment by sohamganatra** [comment]
I was able to replicate this error. We should have this corrected by tom. Thanks for reporting.
