### ISSUE TITLE
dashboard open

### ISSUE THREAD

**Issue by yanxiaochuan** [ComposioHQ/composio#279]
Will the dashboard be open source later?

**Comment by sohamganatra** [comment]
Yes, we are figuring out a good way to do it.

**Comment by yanxiaochuan** [comment]
> Yes, we are figuring out a good way to do it.

Looking forward to release soon，thanks!

**Comment by yanxiaochuan** [comment]
Wow, it's unbelievable. It's amazing

Has it already been achieved? 
Do you have any operation documents?
