### ISSUE TITLE
On-prem / self-hosting option

### ISSUE THREAD

**Issue by ChristianWeyer** [ComposioHQ/composio#291]
I really like what I am seeing :-).

There are a number of customers who would want (and need) a non-SaaS / non-Cloud version of this.

Just like they can have e.g. observability with Langfuse, but self-host it on their premises (https://langfuse.com/docs/deployment/self-host).

Are you also planning this (like a Docker container)?

Thanks!

**Comment by sohamganatra** [comment]
We support it already. It's a part of our paid offering. Would you be open to getting on a call sometime? Calendar Link: https://cal.com/team/composio/chat-with-soham

**Comment by ChristianWeyer** [comment]
Hi :-),

Hey!

No need for a call. :-)

In good old Europe, there are a number of customers who still want (or need) an on-prem deployment.
I could not find an on-prem option on your website, thus I was creating this issue.

We are a tech consulting company working with various ISV and enterprise customers.

Thanks!

**Comment by sohamganatra** [comment]
Make's sense. Totally a miss on my part. Feel free to ping me anytime at soham@composio.dev, if you want to initiate a conversation about on-prem deployment. We will soon add it to website. 

Thinktecture looks really cool and would love to talk more about how Composio can fit into your use cases.

**Comment by ChristianWeyer** [comment]
Thanks @sohamganatra!

**Comment by arkodeep3404** [comment]
is self host available yet??
