### ISSUE TITLE
500 Internal Server Error When Accessing 150+ External Tools Link

### ISSUE THREAD

**Issue by Bhavik-Jikadara** [ComposioHQ/composio#353]
Hi,

I encountered an issue on the [150+ external tools](https://composio.dev/tools/list/all). When I click the "150+ external tools" link, I receive a "500 Internal Server Error." This error prevents me from accessing the list of external tools and their integrations.

Screenshot:
![Screenshot 2024-07-22 105702](https://github.com/user-attachments/assets/d40803a9-c737-41b8-98ba-8605a914bd07)

Best regards,
Bhavik Jikadara

**Comment by Karthikeya-Meesala** [comment]
hey @Bhavik-Jikadara - thanks a lot for pointing it out and we just fixed it. I am now closing this issue now.

If you found any other issues on the docs, feel free to raise a PR :)

**Comment by Bhavik-Jikadara** [comment]
@Karthikeya-Meesala Sure, thank you
