### ISSUE TITLE
zsh: command not found: composio

### ISSUE THREAD

**Issue by kuntal-c** [ComposioHQ/composio#381]
composio add github
zsh: command not found: composio

**Comment by sohamganatra** [comment]
Hey you need to install `composio-core` for `composio cli`

can you try first command pip install composio-core.

**Comment by kuntal-c** [comment]
Yes I did pip install composite-core,  but still the same issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kuntal-c** [comment]
I mean composio-core

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kuntal-c** [comment]
Has this issue been resolved? What's the resolution ?
