### ISSUE TITLE
🐛 Bug Report: `sed` command not working perfect on mac (inside various `setup.sh` files of examples)

### ISSUE THREAD

**Issue by r1jsheth** [ComposioHQ/composio#465]
`sed` command is not behaving correctly in my mac.
This is a minor bug, I faced while playing with a couple of examples.

While executing `setup.sh` of `sql_agent` example, I correctly entered my OpenAI environment key on terminal but it did not reflect in the newly created `.env` file

Following line
```
sed -i "s/^OPENAI_API_KEY=.*$/OPENAI_API_KEY=$OPENAI_API_KEY/" .env
```

It is part of multiple setup files.

I will also provide a FIX PR for this.

**Comment by sohamganatra** [comment]
This has been solved. And merged to master! Thanks @r1jsheth for your contribution! :)
