### ISSUE TITLE
🐛 Bug Report: 1 click ATO

### ISSUE THREAD

**Issue by ElcapitanoO7x** [ComposioHQ/composio#499]
here all report for 3 bugs 
https://huntr.com/bounties/6b6c3cea-b958-4db3-9322-14e0fc5a284f
https://huntr.com/bounties/a6ab0896-a628-47ca-bdf4-3f05ce2068f4
https://huntr.com/bounties/578d5244-b73d-4e70-92ce-d6f9f59b6a1e

**Comment by plxity** [comment]
This is fixed
