### ISSUE TITLE
Bug: Invalid route on `app.composio.dev/dashboard`

### ISSUE THREAD

**Issue by kartikmehta8** [ComposioHQ/composio#513]
### Reproduce the bug
1. Click on `App` 
![Screenshot 2024-08-31 at 00 33 12](https://github.com/user-attachments/assets/26afd2b1-f934-4979-9f3e-4bb3910c0023)
2. You can see it redirects to invalid route
![image](https://github.com/user-attachments/assets/70f3f5b1-1eff-40f1-849c-947fd64abdf6)
3. It should be `https://app.composio.dev/apps?category=all` or maybe `https://app.composio.dev/apps`

---
I found this project through a Dev.to post and would love to contribute meaningfully to the project. I am [kartik](https://mrmehta.in) :)

**Comment by himanshu-dixit** [comment]
Thanks for reporting this @kartikmehta8 🙌🏻 . The fix for this has been released.
