### ISSUE TITLE
Bug: Null-valued logs are created after configuring the GitHub trigger.

### ISSUE THREAD

**Issue by kartikmehta8** [ComposioHQ/composio#514]
Every time I create a new trigger integration for GitHub (successfully), some `null-valued` logs are being created that point to no connection. *Is this the expected behavior?*

![Screenshot 2024-08-31 at 11 30 50](https://github.com/user-attachments/assets/6f75efeb-c361-409b-897d-96d5d7c3ce49)

When you click on Connection for any of these, it goes nowhere.

![Screenshot 2024-08-31 at 11 33 23](https://github.com/user-attachments/assets/e31fba18-67da-403e-a2e9-1857283de1f5)

This just loads infinitely.

**Comment by kartikmehta8** [comment]
Also, I created 4 triggers, 2 for Commit and 2 for PR.
![Screenshot 2024-08-31 at 11 45 22](https://github.com/user-attachments/assets/aa8bf5b9-ca8e-424d-88e1-f3a39a9acd39)
Still, it is showing 0 here,
![image](https://github.com/user-attachments/assets/751ee9e7-44e1-4349-8dbc-5a530313333d)

**Comment by sohamganatra** [comment]
@kartikmehta8 , we just found the issue. This should be corrected soon!

**Comment by utkarsh-dixit** [comment]
@kartikmehta8 Thanks for reporting the issue, this was resolved and fixed we days back.
