### ISSUE TITLE
Simple GMAIL_FETCH_EMAILS running infinitely

### ISSUE THREAD

**Issue by bhupixb** [ComposioHQ/composio#542]
Hey guys,
I am new to Composio. I was trying it out for the first time.
I am trying to fetch some gmails via Python. Here's the code snippet:
Version:
```shell
composio_core             0.5.13
composio_openai           0.5.13
```

```python
from composio_openai import ComposioToolSet, Action

tool_set = ComposioToolSet()
tools = tool_set.get_tools(actions=[Action.GMAIL_FETCH_EMAILS])

print('done')
```

Apparently the code is stuck at _tool_set.get_ because the message done is never printed.

I tried to enabled debug logs and can see that it's making thousands of calls like below(are they really needed). Am I doing something wrong?

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/5f51e87b-497c-4dc4-805f-4ae47dd65c79">

My usecase is simply:
1. get some emails matching a subject(haven't been able to figure out yet, how to pass the subject). In Composio Website, I'm able to pass subject btw.
2. Get attachments for each email and do some parsing. I am trying out OpenAI btw.

Please let me know if I am missing something.

**Comment by sohamganatra** [comment]
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/434fd191-c0a7-4507-a63f-71f8cfa3bbdc">
Hey it worked really nicely for me. I am unable to replicate this. Would you be open to testing this again and letting me know. If yes, can run it in debug mode and share all the logs. 

Sorry for the trouble.

**Comment by bhupixb** [comment]
Hi Soham, thanks for responding.

I'm getting a different error now smh:
<img width="1275" alt="image" src="https://github.com/user-attachments/assets/b9892c7e-bb7a-4fc3-a50b-82648a44d903">


Btw I was able to make it work with different code actually, works seamlessly:) Thanks for the super easy integration provided by the composio platform.

New Working code:
```python
from composio import ComposioToolSet, Action
import os
import logging
import json

tool_set = ComposioToolSet(api_key=os.getenv("COMPOSIO_API_KEY"))

try:
    resp = tool_set.execute_action(
        action=Action.GMAIL_FETCH_EMAILS,
        params={"max_results": 3, "query": 'subject: "my subject"'}
    )
    print(json.dumps(resp))
except Exception as ex:
    logging.exception(ex)
```
