### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by LloydVickeryASI** [ComposioHQ/composio#606]
Path: /framework/llamaindex

I'm getting Pydantic errors for every tool imported when using composio_llamaindex. This happens regardless of using App or Action imports. 

`PydanticJsonSchemaWarning: Default value default='desc' description="The direction to sort the results by. Note: choose value only from following options - ['asc', 'desc']. Please provide a value of type string." extra={'examples': []} is not JSON serializable; excluding default from JSON schema [non-serializable-default]`

I'm using composio-llamaindex v0.5.11. I got this error with all tools tried so far (Github and Hubspot to start).

**Comment by Karthikeya-Meesala** [comment]
Hey, Thanks for pointing this out. 

This issue is already on our radar and we're pushing fixes. This should resolved by the end of the week.
