### ISSUE TITLE
self host on vm

### ISSUE THREAD

**Issue by arkodeep3404** [ComposioHQ/composio#642]
how to self host this on my VM??

i get this error:
[2024-09-26 18:56:15,571][DEBUG] Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/composio/cli/utils/decorators.py", line 36, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/composio/c...
Error: API Key not provided, either provide API key or export it as `COMPOSIO_API_KEY` or run `composio login`

**Comment by arkodeep3404** [comment]
i tried 2 days back and yes I got the same thing 

lmk if you guys decide to fix it

**Comment by apneduniya** [comment]
@arkodeep3404 Could you join our discord server (https://discord.gg/UcQ6zKRPnY) and just create a post at `🖥│support-forum` channel mentioning this issue, I will connect with you regarding this issue from there :raised_hands:

**Comment by arkodeep3404** [comment]
ok sure thanks 
will do it

**Comment by arkodeep3404** [comment]
here is the link

https://discord.com/channels/1170785031560646836/1292916324686631003

**Comment by nikhil-pandey** [comment]
Any updates on this?
Is it not possible to use the tools locally without providing an API key out of the box?

**Comment by plxity** [comment]
@nikhil-pandey API key is required to use TS SDK

**Comment by plxity** [comment]
We don't support VM as of now, might look into it later.
