### ISSUE TITLE
Feature request: Receive Account/Management events via webhook

### ISSUE THREAD

**Issue by AhnanAzh** [ComposioHQ/composio#647]
I'm currently experimenting with Composio to integrate it into a SaaS application I'm building. The current issue I'm facing is that there's no way to get notified about asynchronous events such as adding a new integration, enabling or disabling an integration, new connected account successfully added etc. Additionally, to fully integrate, I want to keep track of all the available (integrated) tools and actions of those tools (at least important details such as IDs) in our database.

I believe that if you support pushing real-time events for such use cases (or generally any account-level events), this would solve many of the integration issues and allow our backend to keep in sync with Composio.

If you have any other alternative solutions, please feel free to suggest them to me.

**Comment by kartikey369-ind** [comment]
Webhook for Account Management Events: 
Implement a webhook system to push real-time notifications for important events such as: 
1.Adding a new integration
2.Enabling or disabling an integration
3.Successfully adding a new connected account

Event Tracking: 
1.Ensure that the webhook payload includes essential details for each event, such as integration IDs and status changes.

2.This will enable your backend to remain synchronized with Composio by processing the received events and updating your database accordingly.

**Comment by sohamganatra** [comment]
This has been added and is live now.
