### ISSUE TITLE
[Docs] Quick start 3 example doesn't incorporate the AI model

### ISSUE THREAD

**Issue by Priyansh121096** [ComposioHQ/composio#675]
Hello, 

I was reading through [this example on the docs](https://docs.composio.dev/introduction/intro/quickstart_3) and noticed that even though the OpenAI client is initialized in step#4, it is not used in the callback of the trigger in step#5. And then in the "What just happened?" section, it says that we "Instructed the AI to list all emails received" which I believe isn't accurate (or am I missing something?).

Do you think it's better for illustration purposes if we let the AI client do something in the callback like maybe summarize the email or something?

Best,
Priyansh

**Comment by Priyansh121096** [comment]
Maybe we can use one of the examples from https://github.com/ComposioHQ/composio/tree/master/python/examples/advanced_agents/scheduler_agent?

**Comment by plxity** [comment]
@Priyansh121096 Thanks for creating the issue. Would you like to work on this?

**Comment by plxity** [comment]
@abhishekpatil4 Can you look into this?

**Comment by abhishekpatil4** [comment]
@Priyansh121096 the issue has been fixed.
