### ISSUE TITLE
Implement messages to celebrate successful PR contributions

### ISSUE THREAD

**Issue by Mayank77maruti** [ComposioHQ/composio#705]
Provide congratulatory messages when a new contributor submits their first and second PRs or more.

The Solution:-
We will add a GitHub Action that will trigger when a PR gets merged into the main branch.

I would love to implement it.

**Comment by himanshu-dixit** [comment]
@Mayank77maruti That sound awesome. Feel free to create a PR for this 🚀, lmk if you need any help.

**Comment by Mayank77maruti** [comment]
Hey @himanshu-dixit , I have pr regarding this issue please do review it.
Thank you.

**Comment by Mayank77maruti** [comment]
Hey @himanshu-dixit , I have participated in an open source contribution competition and it would be really great if you can review this pr. I am really sorry for disturbing your busy schedule but it would really a big help if you can review it.
Thank you.
