### ISSUE TITLE
Discord link broken 

### ISSUE THREAD

**Issue by ianjamesburke** [ComposioHQ/composio#814]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/4a3925eb-6c70-4c49-8254-e863a70d38aa">

link invalid.

**Comment by ianjamesburke** [comment]
Would love to join the beta

**Comment by himanshu-dixit** [comment]
Hey @ianjamesburke!

Discord link seems to be valid on my end. Can you share some recording for this?

**Comment by ianjamesburke** [comment]
Oh! thank you for clarifying, turns out it was an issue with my discord. Sorry about that!
