### ISSUE TITLE
Error: Connection aborted. RemoteDisconnected

### ISSUE THREAD

**Issue by greg80303** [ComposioHQ/composio#839]
I'm seeing the following error randomly when using Composio tools.  I'm using Langchain integration and Google tools right now (Email, Tasks, Calendar), but I don't think it has to do with the specific tool.  I'm thinking this is some sort of issue with the communications to the Composio API

```
Error: ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

This error happens randomly and it happens on all different types of tools and actions.

**Comment by plxity** [comment]
@greg80303 Can you share the code snippet?

**Comment by plxity** [comment]
Closing this issue as there is no update and code to reproduce the issue, feel free to reopen the issue if you face the same problem, Happy to help!
