### ISSUE TITLE
getConnections returns an empty list

### ISSUE THREAD

**Issue by sahildhull2512** [ComposioHQ/composio#847]
I am using the following code to add new tools to composio
`const connection = await entity.initiateConnection(toolName);`
On connect, I am being redirected to auth page of that particular tool, where composio is asking me to authorise it.
So, the tools are getting added.

But when I am getting the list of connected tools in the following line:

`const composioConnectedTools = await entity.getConnections();`

It returns an empty list.

It was working completely fine till yesterday.
I tried a bunch of different versions from npm.

- 0.1.13 (this was what I was using earlier)
- 0.1.17-2
- 0.2.8
- 0.2.8-2
- 0.2.9-5

In all the earlier versions, initiateConnection is itself not working now. Getting the following return value
```
ConnectionRequest {
    connectionStatus: undefined,
    connectedAccountId: undefined,
    redirectUrl: null
  }
```

But in the latest version, initiateConnection is working, but getConnection is not.

My guess is this might be the commit that could be a culprit
https://github.com/ComposioHQ/composio/commit/1ad7d6fca579dd91ed04c39bcc5cd2c94d52dbbe#diff-b22149526ec6104b67529b61629841152ae0eabee1cde026493d1bf21332ecebR79

**Comment by sahildhull2512** [comment]
The following is the code snippet I am using:
```
const toolset = new VercelAIToolSet({
    apiKey: process.env.COMPOSIO_API_KEY!,
});
const entity = await toolset.client.getEntity(userId);
const connection = await entity.initiateConnection(toolName);
if (!connection || !connection.redirectUrl) {
    console.error("Failed to retrieve redirect URL");
    return res.status(500).send("Failed to retrieve redirect URL");
}

vlog(2, "=== CONNECTION ===", {
    "Connection:": connection,
});
```

**Comment by sahildhull2512** [comment]
I tried another method, but this also returns empty list

```
const toolset = new VercelAIToolSet({
    apiKey: process.env.COMPOSIO_API_KEY!,
});
const tools = await toolset.getTools({ actions: ['get_connections'] });
console.log('Tools from Composio:', tools);
```

Can you please tell me what function should I be calling to get the list of tools?

**Comment by plxity** [comment]
This is fixed
