### ISSUE TITLE
WebhookVerificationError: No matching signature found

### ISSUE THREAD

**Issue by almeynman** [ComposioHQ/composio#995]
Hi, I followed the recommended setup for [standard webhooks](https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md) and implemented a simple webhook verification logic

```
from fastapi import APIRouter, Request, Response
from standardwebhooks.webhooks import Webhook

router = APIRouter(prefix="/composio")

@router.post("/webhook/admin")
async def admin_webhook(request: Request) -> Response:
    wh = Webhook(COMPOSIO_WEBHOOK_SECRET)
    body = await request.body()
    payload = wh.verify(body, dict(request.headers))
    print(f"payload: {payload}")
    return Response(status_code=httpx.codes.OK)
```

However the verification fails on `payload = wh.verify(body, dict(request.headers))` with 
```
standardwebhooks.webhooks.WebhookVerificationError: No matching signature found
```

**Comment by plxity** [comment]
@almeynman We have figured the issue, working on fix it. It should be live in next 24 hours.

**Comment by plxity** [comment]
@almeynman This has been fixed, you should be able to verify the signature.

Steps to get the new webhook format

1. Go the Dashboard - https://app.composio.dev/
2. Go to settings / Events and Triggers - https://app.composio.dev/events_and_triggers
3. **Switch on** the toggle to subscribe to new webhook format.

<img width="576" alt="Screenshot 2024-12-17 at 7 36 58 PM" src="https://github.com/user-attachments/assets/eae71e95-3e1d-47ae-a6ea-f82165fadf63" />

**Comment by plxity** [comment]
Let me know if you have any questions, Closing this issue for now.
